### ISSUE TITLE
抖音的好像也失效了，一直报id错误

### ISSUE THREAD

**Issue by kudouxinyi** [CharlesPikachu/videodl#16]
抖音的好像也失效了，一直报id错误

**Comment by tisttsf** [comment]
解决了吗?

**Comment by tisttsf** [comment]
报id错误是那个网页改了吧 找不到`dytk`

**Comment by tisttsf** [comment]
> 抖音的好像也失效了，一直报id错误

`https://www.amemv.com/share/user/102064772608` 示例那个id不行啊,用移动设备手动访问也上不去, 我试了几个也不行
`加载失败,请重试`

**Comment by CharlesPikachu** [comment]
新版的视频下载器正在路上，目前已经支持抖音视频根据用户链接进行批量下载~
