### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'click'

### ISSUE THREAD

**Issue by chengyuan19** [CharlesPikachu/videodl#20]
**Environment (使用环境)**
pycharm 2022

- Installation method (安装方式): pip install
- The version of videofetch (版本号): 0.1.8
- Operating system (操作系统): windows10
- Python version (Python版本): 3.10.4

**Question description (问题描述)**
找不到模块click

**Screenshot (报错截图)**
![image](https://user-images.githubusercontent.com/87970169/168455748-6291a8cf-3f19-42c4-ba80-1d8e09023fe0.png)

**Comment by CharlesPikachu** [comment]
run `pip install click`
